//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIBanking.com.quantiguous.api.FundsTransferByCustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.quantiguous.com/services", ConfigurationName="com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService" +
        "")]
    public interface fundsTransferByCustomerService {
        
        // CODEGEN: Generating message contract since the operation transfer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/transfer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse1 transfer(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/transfer", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse1> transferAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest request);
        
        // CODEGEN: Generating message contract since the operation payInvoice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/payInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse1 payInvoice(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/payInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse1> payInvoiceAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest request);
        
        // CODEGEN: Generating message contract since the operation getStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse1 getStatus(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse1> getStatusAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation getBalance is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse1 getBalance(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/getBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse1> getBalanceAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class transfer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string debitAccountNoField;
        
        private beneficiaryType beneficiaryField;
        
        private System.Nullable<transferTypeType> transferTypeField;
        
        private System.Nullable<currencyCodeType> transferCurrencyCodeField;
        
        private float transferAmountField;
        
        private string remitterToBeneficiaryInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string debitAccountNo {
            get {
                return this.debitAccountNoField;
            }
            set {
                this.debitAccountNoField = value;
                this.RaisePropertyChanged("debitAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public beneficiaryType beneficiary {
            get {
                return this.beneficiaryField;
            }
            set {
                this.beneficiaryField = value;
                this.RaisePropertyChanged("beneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<transferTypeType> transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<currencyCodeType> transferCurrencyCode {
            get {
                return this.transferCurrencyCodeField;
            }
            set {
                this.transferCurrencyCodeField = value;
                this.RaisePropertyChanged("transferCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string remitterToBeneficiaryInfo {
            get {
                return this.remitterToBeneficiaryInfoField;
            }
            set {
                this.remitterToBeneficiaryInfoField = value;
                this.RaisePropertyChanged("remitterToBeneficiaryInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class beneficiaryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("beneficiaryCode", typeof(string), DataType="token", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("beneficiaryDetail", typeof(beneficiaryDetailType), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class beneficiaryDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private nameType beneficiaryNameField;
        
        private AddressType beneficiaryAddressField;
        
        private contactType beneficiaryContactField;
        
        private string beneficiaryAccountNoField;
        
        private string beneficiaryIFSCField;
        
        private string beneficiaryMobileNoField;
        
        private string beneficiaryMMIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public nameType beneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
                this.RaisePropertyChanged("beneficiaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AddressType beneficiaryAddress {
            get {
                return this.beneficiaryAddressField;
            }
            set {
                this.beneficiaryAddressField = value;
                this.RaisePropertyChanged("beneficiaryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public contactType beneficiaryContact {
            get {
                return this.beneficiaryContactField;
            }
            set {
                this.beneficiaryContactField = value;
                this.RaisePropertyChanged("beneficiaryContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string beneficiaryAccountNo {
            get {
                return this.beneficiaryAccountNoField;
            }
            set {
                this.beneficiaryAccountNoField = value;
                this.RaisePropertyChanged("beneficiaryAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string beneficiaryIFSC {
            get {
                return this.beneficiaryIFSCField;
            }
            set {
                this.beneficiaryIFSCField = value;
                this.RaisePropertyChanged("beneficiaryIFSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string beneficiaryMobileNo {
            get {
                return this.beneficiaryMobileNoField;
            }
            set {
                this.beneficiaryMobileNoField = value;
                this.RaisePropertyChanged("beneficiaryMobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string beneficiaryMMID {
            get {
                return this.beneficiaryMMIDField;
            }
            set {
                this.beneficiaryMMIDField = value;
                this.RaisePropertyChanged("beneficiaryMMID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class nameType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fullName", Order=0)]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class taxDeductedAtSourceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sectionCodeField;
        
        private string sectionNameField;
        
        private float deductionRateField;
        
        private float deductedAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string sectionCode {
            get {
                return this.sectionCodeField;
            }
            set {
                this.sectionCodeField = value;
                this.RaisePropertyChanged("sectionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string sectionName {
            get {
                return this.sectionNameField;
            }
            set {
                this.sectionNameField = value;
                this.RaisePropertyChanged("sectionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float deductionRate {
            get {
                return this.deductionRateField;
            }
            set {
                this.deductionRateField = value;
                this.RaisePropertyChanged("deductionRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float deductedAmount {
            get {
                return this.deductedAmountField;
            }
            set {
                this.deductedAmountField = value;
                this.RaisePropertyChanged("deductedAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class taxAppliedItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private taxAppliedItemTaxType taxTypeField;
        
        private string accountingCodeField;
        
        private string accountingNameField;
        
        private float taxRateField;
        
        private float taxAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public taxAppliedItemTaxType taxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
                this.RaisePropertyChanged("taxType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
        public string accountingCode {
            get {
                return this.accountingCodeField;
            }
            set {
                this.accountingCodeField = value;
                this.RaisePropertyChanged("accountingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string accountingName {
            get {
                return this.accountingNameField;
            }
            set {
                this.accountingNameField = value;
                this.RaisePropertyChanged("accountingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float taxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
                this.RaisePropertyChanged("taxRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float taxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("taxAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public enum taxAppliedItemTaxType {
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        VAT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class invoiceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string purchaseOrderNumberField;
        
        private string invoiceNumberField;
        
        private System.Nullable<System.DateTime> invoiceDateField;
        
        private System.Nullable<float> invoiceAmountField;
        
        private System.Nullable<float> passedAmountField;
        
        private taxAppliedItem[] taxesAppliedField;
        
        private taxDeductedAtSourceType taxDeductedAtSourceField;
        
        private System.Nullable<float> otherDeductionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string purchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
                this.RaisePropertyChanged("purchaseOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("invoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> invoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("invoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<float> invoiceAmount {
            get {
                return this.invoiceAmountField;
            }
            set {
                this.invoiceAmountField = value;
                this.RaisePropertyChanged("invoiceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<float> passedAmount {
            get {
                return this.passedAmountField;
            }
            set {
                this.passedAmountField = value;
                this.RaisePropertyChanged("passedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("taxItem", IsNullable=false)]
        public taxAppliedItem[] taxesApplied {
            get {
                return this.taxesAppliedField;
            }
            set {
                this.taxesAppliedField = value;
                this.RaisePropertyChanged("taxesApplied");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public taxDeductedAtSourceType taxDeductedAtSource {
            get {
                return this.taxDeductedAtSourceField;
            }
            set {
                this.taxDeductedAtSourceField = value;
                this.RaisePropertyChanged("taxDeductedAtSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<float> otherDeductions {
            get {
                return this.otherDeductionsField;
            }
            set {
                this.otherDeductionsField = value;
                this.RaisePropertyChanged("otherDeductions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class supplierDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private nameType supplierNameField;
        
        private AddressType supplierAddressField;
        
        private contactType supplierContactField;
        
        private string supplierAccountNoField;
        
        private string supplierIFSCField;
        
        private string supplierMobileNoField;
        
        private string supplierMMIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public nameType supplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
                this.RaisePropertyChanged("supplierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public AddressType supplierAddress {
            get {
                return this.supplierAddressField;
            }
            set {
                this.supplierAddressField = value;
                this.RaisePropertyChanged("supplierAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public contactType supplierContact {
            get {
                return this.supplierContactField;
            }
            set {
                this.supplierContactField = value;
                this.RaisePropertyChanged("supplierContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string supplierAccountNo {
            get {
                return this.supplierAccountNoField;
            }
            set {
                this.supplierAccountNoField = value;
                this.RaisePropertyChanged("supplierAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string supplierIFSC {
            get {
                return this.supplierIFSCField;
            }
            set {
                this.supplierIFSCField = value;
                this.RaisePropertyChanged("supplierIFSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string supplierMobileNo {
            get {
                return this.supplierMobileNoField;
            }
            set {
                this.supplierMobileNoField = value;
                this.RaisePropertyChanged("supplierMobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string supplierMMID {
            get {
                return this.supplierMMIDField;
            }
            set {
                this.supplierMMIDField = value;
                this.RaisePropertyChanged("supplierMMID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string stateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
                this.RaisePropertyChanged("stateOrProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class contactType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileNoField;
        
        private string emailIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("mobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string emailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
                this.RaisePropertyChanged("emailID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class supplierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supplierCode", typeof(string), DataType="token", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("supplierDetail", typeof(supplierDetailType), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class transactionStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private transactionStatusTypeStatusCode statusCodeField;
        
        private string subStatusCodeField;
        
        private string bankReferenceNoField;
        
        private string beneficiaryReferenceNoField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public transactionStatusTypeStatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string subStatusCode {
            get {
                return this.subStatusCodeField;
            }
            set {
                this.subStatusCodeField = value;
                this.RaisePropertyChanged("subStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bankReferenceNo {
            get {
                return this.bankReferenceNoField;
            }
            set {
                this.bankReferenceNoField = value;
                this.RaisePropertyChanged("bankReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string beneficiaryReferenceNo {
            get {
                return this.beneficiaryReferenceNoField;
            }
            set {
                this.beneficiaryReferenceNoField = value;
                this.RaisePropertyChanged("beneficiaryReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public enum transactionStatusTypeStatusCode {
        
        /// <remarks/>
        ONHOLD,
        
        /// <remarks/>
        SENT_TO_BENEFICIARY,
        
        /// <remarks/>
        COMPLETED,
        
        /// <remarks/>
        RETURNED_FROM_BENEFICIARY,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        IN_PROCESS,
        
        /// <remarks/>
        SCHEDULED_FOR_NEXT_WORKDAY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum transferTypeType {
        
        /// <remarks/>
        NEFT,
        
        /// <remarks/>
        IMPS,
        
        /// <remarks/>
        RTGS,
        
        /// <remarks/>
        FT,
        
        /// <remarks/>
        ANY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum currencyCodeType {
        
        /// <remarks/>
        INR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class transferResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        private string attemptNoField;
        
        private transferTypeType transferTypeField;
        
        private System.Nullable<bool> lowBalanceAlertField;
        
        private transactionStatusType transactionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string attemptNo {
            get {
                return this.attemptNoField;
            }
            set {
                this.attemptNoField = value;
                this.RaisePropertyChanged("attemptNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public transferTypeType transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> lowBalanceAlert {
            get {
                return this.lowBalanceAlertField;
            }
            set {
                this.lowBalanceAlertField = value;
                this.RaisePropertyChanged("lowBalanceAlert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public transactionStatusType transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transfer transfer;
        
        public transferRequest() {
        }
        
        public transferRequest(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transfer transfer) {
            this.transfer = transfer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse transferResponse;
        
        public transferResponse1() {
        }
        
        public transferResponse1(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse transferResponse) {
            this.transferResponse = transferResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class payInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string customerIDField;
        
        private string debitAccountNoField;
        
        private supplierType supplierField;
        
        private System.Nullable<transferTypeType> transferTypeField;
        
        private System.Nullable<currencyCodeType> paymentCurrencyField;
        
        private System.Nullable<float> netPayableAmountField;
        
        private invoiceType invoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string debitAccountNo {
            get {
                return this.debitAccountNoField;
            }
            set {
                this.debitAccountNoField = value;
                this.RaisePropertyChanged("debitAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public supplierType supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
                this.RaisePropertyChanged("supplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<transferTypeType> transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<currencyCodeType> paymentCurrency {
            get {
                return this.paymentCurrencyField;
            }
            set {
                this.paymentCurrencyField = value;
                this.RaisePropertyChanged("paymentCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<float> netPayableAmount {
            get {
                return this.netPayableAmountField;
            }
            set {
                this.netPayableAmountField = value;
                this.RaisePropertyChanged("netPayableAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public invoiceType invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("invoice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class payInvoiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class payInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoice payInvoice;
        
        public payInvoiceRequest() {
        }
        
        public payInvoiceRequest(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoice payInvoice) {
            this.payInvoice = payInvoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class payInvoiceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse payInvoiceResponse;
        
        public payInvoiceResponse1() {
        }
        
        public payInvoiceResponse1(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse payInvoiceResponse) {
            this.payInvoiceResponse = payInvoiceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string requestReferenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string requestReferenceNo {
            get {
                return this.requestReferenceNoField;
            }
            set {
                this.requestReferenceNoField = value;
                this.RaisePropertyChanged("requestReferenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private transferTypeType transferTypeField;
        
        private transferTypeType reqTransferTypeField;
        
        private System.DateTime transactionDateField;
        
        private float transferAmountField;
        
        private currencyCodeType transferCurrencyCodeField;
        
        private transactionStatusType transactionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public transferTypeType transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public transferTypeType reqTransferType {
            get {
                return this.reqTransferTypeField;
            }
            set {
                this.reqTransferTypeField = value;
                this.RaisePropertyChanged("reqTransferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public currencyCodeType transferCurrencyCode {
            get {
                return this.transferCurrencyCodeField;
            }
            set {
                this.transferCurrencyCodeField = value;
                this.RaisePropertyChanged("transferCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public transactionStatusType transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatus getStatus;
        
        public getStatusRequest() {
        }
        
        public getStatusRequest(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatus getStatus) {
            this.getStatus = getStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse getStatusResponse;
        
        public getStatusResponse1() {
        }
        
        public getStatusResponse1(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse getStatusResponse) {
            this.getStatusResponse = getStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBalance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string appIDField;
        
        private string customerIDField;
        
        private string accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("appID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBalanceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private currencyCodeType accountCurrencyCodeField;
        
        private float accountBalanceAmountField;
        
        private System.Nullable<bool> lowBalanceAlertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public currencyCodeType accountCurrencyCode {
            get {
                return this.accountCurrencyCodeField;
            }
            set {
                this.accountCurrencyCodeField = value;
                this.RaisePropertyChanged("accountCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float accountBalanceAmount {
            get {
                return this.accountBalanceAmountField;
            }
            set {
                this.accountBalanceAmountField = value;
                this.RaisePropertyChanged("accountBalanceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> lowBalanceAlert {
            get {
                return this.lowBalanceAlertField;
            }
            set {
                this.lowBalanceAlertField = value;
                this.RaisePropertyChanged("lowBalanceAlert");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalance getBalance;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalance getBalance) {
            this.getBalance = getBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse getBalanceResponse;
        
        public getBalanceResponse1() {
        }
        
        public getBalanceResponse1(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse getBalanceResponse) {
            this.getBalanceResponse = getBalanceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface fundsTransferByCustomerServiceChannel : APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fundsTransferByCustomerServiceClient : System.ServiceModel.ClientBase<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService>, APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService {
        
        public fundsTransferByCustomerServiceClient() {
        }
        
        public fundsTransferByCustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public fundsTransferByCustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fundsTransferByCustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fundsTransferByCustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse1 APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.transfer(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest request) {
            return base.Channel.transfer(request);
        }
        
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse transfer(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transfer transfer1) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest();
            inValue.transfer = transfer1;
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse1 retVal = ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).transfer(inValue);
            return retVal.transferResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse1> APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.transferAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest request) {
            return base.Channel.transferAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferResponse1> transferAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transfer transfer) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.transferRequest();
            inValue.transfer = transfer;
            return ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).transferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse1 APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.payInvoice(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest request) {
            return base.Channel.payInvoice(request);
        }
        
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse payInvoice(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoice payInvoice1) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest();
            inValue.payInvoice = payInvoice1;
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse1 retVal = ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).payInvoice(inValue);
            return retVal.payInvoiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse1> APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.payInvoiceAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest request) {
            return base.Channel.payInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceResponse1> payInvoiceAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoice payInvoice) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.payInvoiceRequest();
            inValue.payInvoice = payInvoice;
            return ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).payInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse1 APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.getStatus(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest request) {
            return base.Channel.getStatus(request);
        }
        
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse getStatus(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatus getStatus1) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest();
            inValue.getStatus = getStatus1;
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse1 retVal = ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).getStatus(inValue);
            return retVal.getStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse1> APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.getStatusAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest request) {
            return base.Channel.getStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusResponse1> getStatusAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatus getStatus) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getStatusRequest();
            inValue.getStatus = getStatus;
            return ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).getStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse1 APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.getBalance(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse getBalance(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalance getBalance1) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest();
            inValue.getBalance = getBalance1;
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse1 retVal = ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).getBalance(inValue);
            return retVal.getBalanceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse1> APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService.getBalanceAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest request) {
            return base.Channel.getBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceResponse1> getBalanceAsync(APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalance getBalance) {
            APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest inValue = new APIBanking.com.quantiguous.api.FundsTransferByCustomerService.getBalanceRequest();
            inValue.getBalance = getBalance;
            return ((APIBanking.com.quantiguous.api.FundsTransferByCustomerService.fundsTransferByCustomerService)(this)).getBalanceAsync(inValue);
        }
    }
}
